version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak_data:/opt/jboss/keycloak/standalone/data
    command: ["start-dev"]
    networks:
      - keycloak-network
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: bitnami/mariadb:latest
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=Password123!
      - MARIADB_DATABASE=webpot
    ports:
      - "3306:3306" # Expose MariaDB port 3306
    networks:
      - keycloak-network
    restart: always

networks:
  keycloak-network:

volumes:
  mariadb_data:
